apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-sync-sa
  namespace: bucket-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bucket-sync-role
  namespace: bucket-sync
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bucket-sync-role-binding
  namespace: bucket-sync
subjects:
- kind: ServiceAccount
  name: bucket-sync-sa
  namespace: bucket-sync
roleRef:
  kind: Role
  name: bucket-sync-role
  apiGroup: rbac.authorization.k8s.io
